<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Анализ-данных" data-toc-modified-id="Анализ-данных-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Анализ данных</a></span></li><li><span><a href="#Построение-моделей" data-toc-modified-id="Построение-моделей-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Построение моделей</a></span><ul class="toc-item"><li><span><a href="#LinearRegression-из-библиотеки-sklearn" data-toc-modified-id="LinearRegression-из-библиотеки-sklearn-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>LinearRegression из библиотеки sklearn</a></span></li><li><span><a href="#Модель-LinearRegression-на-Python" data-toc-modified-id="Модель-LinearRegression-на-Python-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Модель LinearRegression на Python</a></span></li></ul></li><li><span><a href="#Кодирование-данных" data-toc-modified-id="Кодирование-данных-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Кодирование данных</a></span><ul class="toc-item"><li><span><a href="#Создание-матрицы" data-toc-modified-id="Создание-матрицы-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Создание матрицы</a></span></li><li><span><a href="#Кодирование-признаков" data-toc-modified-id="Кодирование-признаков-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Кодирование признаков</a></span></li></ul></li><li><span><a href="#Алгебраическое-доказательство" data-toc-modified-id="Алгебраическое-доказательство-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Алгебраическое доказательство</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Вывод" data-toc-modified-id="Вывод-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Вывод</a></span></li></ul></div>

# Защита персональных данных клиентов

Предоставлены персональные данные клиентов банка, по этим данным строится модель кредитного скоринга.

Задача: 
- разработать такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию;
- обосновать корректность работы этого метода.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [2]:
df = pd.read_csv('/datasets/insurance.csv')
display(df)
df.info()
print(df.columns)


Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0       1     41.0   49600.0            1                  0
1       0     46.0   38000.0            1                  1
2       0     29.0   21000.0            0                  0
3       0     21.0   41700.0            2                  0
4       1     28.0   26100.0            0                  0
...   ...      ...       ...          ...                ...
4995    0     28.0   35700.0            2                  0
4996    0     34.0   52400.0            1                  0
4997    0     20.0   33900.0            2                  0
4998    1     22.0   32700.0            3                  0
4999    1     28.0   40600.0            1                  0

[5000 rows x 5 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB
Index(['Пол', 'Возраст', 'Зарплата', 'Члены семьи', 'Страховые выплаты'], dtype='object')


## Анализ данных

In [3]:
df = df.drop_duplicates().reset_index(drop=True)
print(df.duplicated().sum())

0


In [4]:
df['Пол'].value_counts()

0    2431
1    2416
Name: Пол, dtype: int64

In [5]:
df['Члены семьи'].value_counts()

1    1748
0    1461
2    1038
3     437
4     124
5      32
6       7
Name: Члены семьи, dtype: int64

In [6]:
df['Возраст'].value_counts()

19.0    213
25.0    205
31.0    202
26.0    201
22.0    201
27.0    201
32.0    196
30.0    196
29.0    196
28.0    196
23.0    195
21.0    193
20.0    190
36.0    186
33.0    186
24.0    176
35.0    173
34.0    173
37.0    143
39.0    140
38.0    135
41.0    124
18.0    116
40.0    110
42.0     93
43.0     77
44.0     74
45.0     73
46.0     60
47.0     47
49.0     37
48.0     26
50.0     26
52.0     22
51.0     21
53.0     11
55.0      9
54.0      7
56.0      5
59.0      3
60.0      2
58.0      2
57.0      2
65.0      1
61.0      1
62.0      1
Name: Возраст, dtype: int64

In [7]:
df['Страховые выплаты'].value_counts()

0    4284
1     423
2     114
3      18
4       7
5       1
Name: Страховые выплаты, dtype: int64

## Построение моделей

In [8]:
features = df.drop(['Страховые выплаты'], axis=1)
target = df['Страховые выплаты'] 

In [9]:
features_train, features_valid, target_train, target_valid = train_test_split(
    features, target, test_size=0.25, random_state=12345)

### LinearRegression из библиотеки sklearn

In [10]:
model = LinearRegression() 
model.fit(features_train, target_train) 
predictions_valid = model.predict(features_valid)

result = r2_score(target_valid, predictions_valid)  
print("R2 модели линейной регрессии на валидационной выборке:", result)

R2 модели линейной регрессии на валидационной выборке: 0.42307727492147584


### Модель LinearRegression на Python 

In [11]:
class LinearRegression2:
    def fit(self, train_features, train_target):
        X = np.concatenate((np.ones((train_features.shape[0], 1)), train_features), axis=1)
        y = train_target
        w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
        self.w = w[1:]
        self.w0 = w[0]

    def predict(self, test_features):
        return test_features.dot(self.w) + self.w0
    
model = LinearRegression2()
model.fit(features_train, target_train)
predictions = model.predict(features_valid)
print(r2_score(target_valid, predictions)

0.4230772749214825


##  Кодирование данных

 ### Создание матрицы 

Главным принципом кодирования данных, для их защиты, здесь является умножение на обратимую матрицу, размерностью совпадающую с размернотстью матрицы признаков.

In [13]:
Z = np.random.normal(size = (4,4))
print(Z)

[[ 0.02490937 -0.58373843  1.46540265 -0.11949976]
 [-0.16313695 -0.55215704 -0.4318525   1.25797059]
 [-0.80640269  0.28919961  0.3450331   0.01795658]
 [ 1.24522788  1.26279801 -1.26547053 -0.26838147]]


Проверка на обратимость:

In [14]:
print(np.linalg.inv(Z))

[[ 0.57240181  0.16019143 -0.54523876  0.45950864]
 [ 0.47367358  0.20152685  1.2343495   0.81628458]
 [ 0.90984113  0.15564373  0.55491745  0.36155197]
 [ 0.59448072  0.95759213  0.66158038  0.54199776]]


### Кодирование признаков 

In [15]:
features1 = features.dot(Z)
target1 = df['Страховые выплаты']

In [16]:
features_train1, features_valid1, target_train1, target_valid1 = train_test_split(
    features1, target1, test_size=0.25, random_state=12345)

In [17]:
model = LinearRegression() 
model.fit(features_train1, target_train1) 
predictions_valid1 = model.predict(features_valid1)

result = r2_score(target_valid1, predictions_valid1)  
print("R2 модели линейной регрессии на валидационной выборке:", result)

R2 модели линейной регрессии на валидационной выборке: 0.423077274921449


## Алгебраическое доказательство

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Качество линейной регрессии после кодирования не изменится.**

**Обоснование:** У линейной регрессии признаки — это вектор чисел в n-мерном пространстве. Предсказание модели вычисляется так: скалярно умножается вектор признаков на вектор весов , затем к этому произведению прибавляется величина сдвига предсказания. Отсюда следует, что умножение признаков на обратимый вектор не изменит предсказание модели.

$w' = ((XP)^T XP)^{-1} (XP)^T y)$

$w' = (P^TX^T XP)^{-1} (XP)^T y)$

$w' = (P^TX^T XP)^{-1}P^TX^T y)$

$w' = (P^TX^T XP)^{-1}P^TX^T y)$

Разложим для начала $w' = ((XP)^T XP)^{-1} (XP)^T y)$, получим: $w' = (X^TP^TXP)^{-1} (XP)^T y)$

Далее: $w' = (X^T)^{-1}(P^T)^{-1}X^{-1}P^{-1} (XP)^T y)$

 $w' = (X^T)^{-1}(P^T)^{-1}X^{-1}P^{-1}X^TP^T y$
 
Сократим:   $w' = (X^T)^{-1}X^{-1}P^{-1}X^T y$
 
Объединим: $w' = (X^TX)^{-1}P^{-1}X^T y$ 

Переставим: $w' = P^{-1}(X^TX)^{-1}X^T y$ 

Если $w' = P^{-1}w$, где $w = (X^T X)^{-1} X^T y$, то:

$P^{-1}(X^TX)^{-1}X^T y = P^{-1}(X^T X)^{-1} X^T y$

## Алгоритм преобразования

In [18]:
features = features.dot(np.random.normal(size = (features.shape[1],features.shape[1])))

## Проверка алгоритма

In [19]:
features_train, features_valid, target_train, target_valid = train_test_split(
    features, target, test_size=0.25, random_state=12345)

In [20]:
model = LinearRegression() 
model.fit(features_train, target_train) 
predictions_valid = model.predict(features_valid)

result = r2_score(target_valid, predictions_valid)  
print("R2 модели линейной регрессии на валидационной выборке:", result)

R2 модели линейной регрессии на валидационной выборке: 0.4230772749211579


## Вывод

Метод преобразования данных создан и обоснованна его корректность работы.